swagger: "2.0"
info:
  description: "This is the documentation for our microblog-api"
  version: "1.0.0"
  title: "REST API Documentation for microblog-api"
  contact:
    name: "Ravn"
host: "http://localhost:3000"
basePath: "/api-docs"
tags:
  - name: "user"
    description: "CRUD Operations with Users"
  - name: "auth"
    description: "Users Authentication"
  - name: "posts"
    description: "Operations with posts on microblog"
  - name: "comments"
    description: "Operations with comments on posts"
schemes:
  - "https"
  - "http"

#Endpoints

paths:
  #Auth
  /auth/login:
    post:
      tags:
        - "auth"
      summary: "Login into an user account"
      operationId: "login"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "username"
          in: "query"
          description: "The user name for login"
          required: true
          type: "string"
        - name: "password"
          in: "query"
          description: "The password for login in clear text"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          name: "token"
          schema:
            $ref: "#/definitions/Token"
        "400":
          description: "Invalid username/password supplied"
        "501":
          description: "internal server error"

  /auth/logout:
    get:
      tags:
        - "auth"
      summary: "Logs out user session"
      description: ""
      operationId: "logoutUser"
      produces:
        - "application/xml"
        - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"

  #User
  /user:
    post:
      tags:
        - "user"
      summary: "Create user"
      operationId: "createUser"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "successful operation"
          schema:
          $ref: "#/definitions/User"
        "400":
          description: "unauthorized"
        "500":
          description: "Internal Server Error"
  
  /user/{uuid}:
    get:
      tags:
        - "user"
      summary: "Get user by id"
      operationId: "getUserByID"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "uuid"
          in: "path"
          description: "The id of an user to be fetched"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
    put:
      tags:
        - "user"
      summary: "Updated user"
      description: "This can only be done by the same user or an admin user"
      operationId: "updateUser"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "uuid"
          in: "path"
          description: "id of the user that is been updated"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "fields to be updated"
          properties:
            firstName:
              type: "string"
            lastName:
              type: "string"
            email:
              type: "string"
      responses:
        "200":
          description: "operation completed succesfully"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid user supplied"
        "404":
          description: "User not found"
    delete:
      tags:
        - "user"
      summary: "Delete user"
      description: "This can only be done by a user with admin role"
      operationId: "deleteUser"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "uuid"
          in: "path"
          description: "The id of the user to be deleted"
          required: true
          type: "string"
      responses:
        "200":
          description: "operation completed succesfully"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"

  /user/{uuid}/email_public:
    put:
      responses:
        "200":
          description: "operation completed succesfully"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"

  /user/{uuid}/name_public:
    tags:
      responses:
        "200":
          description: "operation completed succesfully"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
  #Posts
  /posts:
    post:
      tags:
        - "posts"
      summary: "Creates a new post"
      operationId: "createPost"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "post"
          description: "Created Post"
          required: true
          schema:
            $ref: "#/definitions/Post"
      responses:
          "200":
            description: "successful operation"
          "401":
            description: "unauthorized"
          "501":
            description: "internal server error"
  /posts/getAll:
    get:
      tags:
        - "posts"
      summary: "Gets an array of Posts"
      operationId: "getAll"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "posts"
          description: "Get Posts"
          required: true
          data: []
  /posts/{id}:
    get:
      tags:
        - "posts"
      summary: "Gets an especific post"
      operationId: "getPost"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "The id of the post"
          required: true
          responses:
            "200":
              description: "successful operation"
              schema:
              $ref: "#/definitions/Post"
            "400":
              description: "unauthorized"
            "500":
              description: "Internal Server Error"
    delete:
      tags:
        - "posts"
      summary: "Delete one post from db"
      operationId: "deletePost"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "The id from the post being deleted"
          required: true
          responses:
            "200":
              description: "successful operation"
              schema:
              $ref: "#/definitions/Post"
            "400":
              description: "unauthorized"
            "500":
              description: "Internal Server Error"
    put:
      tags:
        - "posts"
      summary: "Modifies a post"
      operationId: "updatePost"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "The id from the post being updated"
          required: true
          responses:
            "200":
              description: "successful operation"
              schema:
              $ref: "#/definitions/Post"
            "400":
              description: "unauthorized"
            "500":
              description: "Internal Server Error"
# Object Definitions
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      uuid:
        type: "UUID"
        format: "string"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      role:
        type: "string"
        description: "User Role"
        enum:
          - "user"
          - "admin"
          - "mod"
      public_email:
        type: "string"
        description: "User email status"
        enum:
          - "public"
          - "private"
      public_name:
        type: "string"
        description: "User real name status"
        enum:
          - "public"
          - "private"
      created_at:
        type: "timestamp"
        format: "datetime"
        description: "user's creation time"
      updated_at:
        type: "timestamp"
        format: "datetime"
        description: "last update on user"
        default: "null"
    xml:
      name: "User"
  Post:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      uuid:
        type: "UUID"
        format: "string"
      user_id: 
        type: "UUID"
        format: "string"
      content:
        type: "string"
      completed:
        type: "boolean"
      likes:
        type: "integer"
        format: "int64"
      dislikes:
        type: "integer"
        format: "int64"
      created_at: 
        type: "timestamp"
        format: "datetime"
        description: "post creation time"
      updated_at: 
        type: "timestamp"
        format: "datetime"
        description: "last update of the post"
    xml:
      name: "Post"
  Comment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      uuid:
        type: "UUID"
        format: "string"
      user_id: 
        type: "UUID"
        format: "string"
      post_id: 
        type: "UUID"
        format: "string"
      content:
        type: "string"
      completed:
        type: "boolean"
      likes:
        type: "integer"
        format: "int64"
      dislikes:
        type: "integer"
        format: "int64"
      created_at: 
        type: "timestamp"
        format: "datetime"
        description: "post creation time"
      updated_at: 
        type: "timestamp"
        format: "datetime"
        description: "last update of the post"
    xml:
      name: "Comment"
  Token: 
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      uuid:
        type: "UUID"
        format: "string"
      user_id: 
        type: "UUID"
        format: "string"
      jti: 
        format: "string"
      aud:
        type: "string"
      created_at: 
        type: "timestamp"
        format: "datetime"
        description: "token creation time"
      xml:
        name: "Token"
